# Generated by Django 6.0.3 on 2026-03-26 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(help_text='Data Inicio da fatura')),
                ('data_fim', models.DateField(help_text='Data Fim da fatura')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada')], help_text='"Aberta" ou "Fechada"', max_length=10)),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
                'db_table': 'tb_faturas',
            },
        ),
        migrations.CreateModel(
            name='ModeloTransacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_transacao', models.CharField(help_text='"A Vista" ou "Parcelado"', max_length=15)),
            ],
            options={
                'verbose_name': 'Modelo de Trasação',
                'verbose_name_plural': 'Modelos de Transações',
                'db_table': 'tb_modelo_transacao',
            },
        ),
        migrations.CreateModel(
            name='TipoTransacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transacao', models.CharField(help_text='"Débito" ou "Crédito"', max_length=10)),
            ],
            options={
                'verbose_name': 'Tipo de Transação',
                'verbose_name_plural': 'Tipos de Transações',
                'db_table': 'tb_tipo_transacao',
            },
        ),
        migrations.CreateModel(
            name='Transacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateField(help_text='Data da transação')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor da transação', max_digits=10)),
                ('descricao', models.CharField(help_text='Descrição da transação/estabelecimento/banco', max_length=70)),
                ('id_externo', models.CharField(blank=True, help_text='Id de itentificação da transação (origem banco)', max_length=100, null=True)),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.faturas')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.modelotransacao')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.tipotransacao')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'db_table': 'tb_transacoes',
            },
        ),
    ]
