# Generated by Django 6.0.3 on 2026-03-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacoes',
            name='parcela_atual',
            field=models.IntegerField(blank=True, help_text='Parcela atual', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='transacoes',
            name='total_parcelas',
            field=models.IntegerField(blank=True, help_text='Total de parcelas', max_length=5, null=True),
        ),
    ]
